version: '3'
services:
  mysql:
    image: mysql:8.0.40
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@123456
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql