version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14.10
    environment:
      - POSTGRES_PASSWORD=Pg@123456
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql